# Generated by Django 2.2.3 on 2019-07-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claims',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
