# Generated by Django 2.2.3 on 2019-07-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0002_auto_20190716_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
