# Generated by Django 2.2.3 on 2019-07-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0004_auto_20190719_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
