# Generated by Django 2.2.3 on 2019-07-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0005_auto_20190719_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='description',
            field=models.CharField(default='Not Seen Yet', max_length=1000),
        ),
    ]
