# Generated by Django 2.2.3 on 2019-07-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0006_auto_20190719_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='status',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
