# Generated by Django 2.2.3 on 2019-07-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0008_auto_20190719_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='claims',
            name='status',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
